#!/bin/bash

CURL="curl"
BASE="${DEQAR_BASE}/submissionapi/v1"

if [ "$1" = "--file" ]; then
	URL="${BASE}/submit/reportfile/$2/`basename $3`"
	METHOD="PUT"
	FILE="$3"
	CTYPE="$4"
	OUTPUT="cat"
else
	URL="${BASE}/submit/report"
	METHOD="POST"
	FILE="$1"
	CTYPE="application/json"
	OUTPUT="json_pp"
fi

$CURL -v -H "Content-type: $CTYPE" -H "Authorization: Bearer $DEQAR_TOKEN" -X$METHOD $URL --data-binary @$FILE | $OUTPUT

echo

